#!/usr/local/bin/fish

source utils.fish

set -x test_json '{"repository":{"name":"rails_sample"}}'
set -x action_file '/Users/kimh/git/zoku/data/rails_sample/action'

### Global variables
set -x data_dir ./data

echo "zoku started"

function build
	set json         $argv[-1]
	set repo_name    (echo $json | jq -r '.repository.name')

	set project_dir  $data_dir/$repo_name
	set builds_dir   $project_dir/builds
	set build_num    (next_build_dir $builds_dir)
	set build_dir    $builds_dir/$build_num
	
	set action       (cat  $action_file | tr '\n' ';')
	
	if test $action
		echo "Buidling $repo_name started..."
		mkdir -p $build_dir
	
		pushd $build_dir
		docker run -e "action=$action" builder fish -c 'eval $action; main' > out.log
		echo "Buidling $repo_name finished!!"
		popd
	else
		echo "$action_file doesn't exist"
	end

end

function next_build_dir
	set builds_dir $argv[1]

	if is_dir_empty $builds_dir
		set newest_build_num 0
	else
		set newest_build_num (ls $builds_dir)[-1]
	end

	echo (math $newest_build_num + 1)
end

#while true
	#sleep 3
	#set github_webhook_json (echo -e 'HTTP/1.1 200 OK\r\n' | nc -l 4567)
	set github_webhook_json $test_json
	set logfile 

	build $github_webhook_json 
#end


